### ISSUE TITLE
Cast to Number failed for value "1/1/1997" at path "yearOfBirth" for model "ValidationFile

### ISSUE THREAD

**Issue by dahowes** [Arsenalist/cff-ranker#41]
Received this error message when trying to upload comp data
![Screen Shot 2021-03-17 at 11 04 48 AM](https://user-images.githubusercontent.com/78503799/111489866-e9ff9600-8710-11eb-9fb2-8420a5dd39a4.png)

**Comment by Arsenalist** [comment]
This was fixed in https://github.com/Arsenalist/cff-ranker/commit/087e66fea415e7d3315dcbd6f4b4362d896312a3
